[mysql]
host = "localhost"
port = 3306
database = "projectdb"
user = "root"
password = "acorn1234"
charset = "utf8mb4"

[dbserver]
server = "localhost\\SQLEXPRESS"
database = "projectdb"
username = "pingu"
password = "vldrn1234"